<template>
  <Teleport to="body">
    <Transition name="modal-fade">
      <div v-if="modelValue" class="modal-backdrop" @click.self="$emit('update:modelValue', false)">
        <Transition name="modal-slide">
          <div v-if="modelValue" class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title">

            <div class="modal-header">
              <div>
                <h2 id="modal-title" class="modal-title">Add New Staff</h2>
                <p class="modal-subtitle">Onboard a new member to the HEKS ecosystem.</p>
              </div>
              <button class="modal-close" @click="$emit('update:modelValue', false)" aria-label="Close">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>

            <div class="avatar-row">
              <label class="avatar-upload" :class="{ 'has-preview': previewUrl }" :style="previewUrl ? `background-image: url(${previewUrl})` : ''">
                <input type="file" accept="image/jpeg,image/png" @change="onFileChange" hidden />
                <template v-if="!previewUrl">
                  <svg class="upload-icon" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                    <rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/>
                    <polyline points="21 15 16 10 5 21"/>
                  </svg>
                  <span class="upload-label">UPLOAD</span>
                </template>
              </label>
              <div class="avatar-meta">
                <p class="avatar-meta-title">PROFILE PICTURE</p>
                <p class="avatar-meta-hint">JPG or PNG, max 2MB. A square ratio works best for station avatars.</p>
              </div>
            </div>

            <div class="form-body">

              <!-- ─────────────────────────────────────────────────────────
                   SECTION: Identity
                   Fields: fullName, displayName
                   API shape: { fullName: string, displayName: string }
              ──────────────────────────────────────────────────────────── -->

              <!-- Full Name -->
              <div class="field-group full">
                <label class="field-label">FULL NAME</label>
                <div class="input-wrap">
                  <input v-model="form.name" class="field-input" type="text" placeholder="e.g. Marcus Chen" :class="{ error: errors.name }" />
                </div>
                <span v-if="errors.name" class="field-error">{{ errors.name }}</span>
              </div>

              <!-- Display Name -->
              <div class="field-group full">
                <label class="field-label">DISPLAY NAME</label>
                <div class="input-wrap">
                  <input
                    v-model="form.displayName"
                    class="field-input"
                    type="text"
                    placeholder="e.g. Marcus C."
                    :class="{ error: errors.displayName }"
                  />
                </div>
                <!-- Hint: auto-suggested from fullName; user can override -->
                <span class="field-hint">Short name shown on station screens. Auto-filled from full name.</span>
                <span v-if="errors.displayName" class="field-error">{{ errors.displayName }}</span>
              </div>

              <!-- ─────────────────────────────────────────────────────────
                   SECTION: Work Assignment
                   Fields: role, shift, employeeId
                   API shape: { role: { id: number, roleName: string }, employeeId: string }
                   TODO: roles list → fetch from GET /api/roles
                   TODO: employeeId → auto-generated by API on POST; shown as read-only after creation
              ──────────────────────────────────────────────────────────── -->

              <!-- Role + Shift -->
              <div class="field-row">
                <div class="field-group">
                  <label class="field-label">ROLE</label>
                  <div class="input-wrap select-wrap">
                    <select v-model="form.role" class="field-input field-select" :class="{ error: errors.role }">
                      <option value="">Select role…</option>
                      <!--
                        TODO: replace `roles` with API data:
                        const roles = await fetch('/api/roles').then(r => r.json())
                        map to: { id: r.id, label: r.roleName }
                      -->
                      <option v-for="r in roles" :key="r.id" :value="r.id">{{ r.label }}</option>
                    </select>
                    <svg class="select-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>
                  </div>
                  <span v-if="errors.role" class="field-error">{{ errors.role }}</span>
                </div>

                <div class="field-group">
                  <label class="field-label">SHIFT</label>
                  <div class="input-wrap select-wrap">
                    <select v-model="form.shift" class="field-input field-select" :class="{ error: errors.shift }">
                      <option value="">Select shift…</option>
                      <option v-for="s in shifts" :key="s.label" :value="s.label">{{ s.display }}</option>
                    </select>
                    <svg class="select-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>
                  </div>
                  <span v-if="errors.shift" class="field-error">{{ errors.shift }}</span>
                </div>
              </div>

              <!-- Employee ID -->
              <!--
                TODO: this field is auto-generated by the API (e.g. "EMP-2026-089").
                For now it's editable; once POST /api/staff returns the created record,
                display the API-assigned ID as read-only on the edit modal instead.
              -->
              <div class="field-group full">
                <label class="field-label">EMPLOYEE ID</label>
                <div class="input-wrap icon-input">
                  <svg class="input-prefix-icon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="2" y="7" width="20" height="14" rx="2"/>
                    <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"/>
                    <line x1="12" y1="12" x2="12" y2="16"/><line x1="10" y1="14" x2="14" y2="14"/>
                  </svg>
                  <input
                    v-model="form.employeeId"
                    class="field-input has-prefix"
                    type="text"
                    placeholder="e.g. EMP-2026-089"
                    :class="{ error: errors.employeeId }"
                  />
                </div>
                <span class="field-hint">Leave blank to let the system auto-assign an ID.</span>
                <span v-if="errors.employeeId" class="field-error">{{ errors.employeeId }}</span>
              </div>

              <!-- ─────────────────────────────────────────────────────────
                   SECTION: Status
                   API shape: { currentStatus: 'ACTIVE' | 'ON_BREAK' | 'OFF_DUTY' }
                   Note: API uses UPPER_SNAKE_CASE; mapped to lowercase kebab in StaffStatus type
              ──────────────────────────────────────────────────────────── -->

              <div class="field-group full">
                <label class="field-label">STATUS</label>
                <div class="status-options">
                  <label
                    v-for="s in statuses"
                    :key="s.value"
                    class="status-option"
                    :class="[s.value, { selected: form.status === s.value }]"
                  >
                    <input type="radio" v-model="form.status" :value="s.value" hidden />
                    <span class="status-dot-sm" :class="s.value"></span>
                    {{ s.label }}
                  </label>
                </div>
              </div>

              <!-- ─────────────────────────────────────────────────────────
                   SECTION: Contact
                   Fields: emailAddress, phoneNumber
                   API shape: { emailAddress: string, phoneNumber: string }
              ──────────────────────────────────────────────────────────── -->

              <!-- Contact Email -->
              <div class="field-group full">
                <label class="field-label">CONTACT EMAIL</label>
                <div class="input-wrap icon-input">
                  <svg class="input-prefix-icon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="2" y="4" width="20" height="16" rx="2"/><polyline points="2 6 12 13 22 6"/>
                  </svg>
                  <input v-model="form.email" class="field-input has-prefix" type="email" placeholder="m.chen@heks-kitchen.com" :class="{ error: errors.email }" />
                </div>
                <span v-if="errors.email" class="field-error">{{ errors.email }}</span>
              </div>

              <!-- Phone Number -->
              <div class="field-group full">
                <label class="field-label">PHONE NUMBER</label>
                <div class="input-wrap icon-input">
                  <svg class="input-prefix-icon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 1.27h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 8.8a16 16 0 0 0 6.29 6.29l.95-.95a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/>
                  </svg>
                  <input
                    v-model="form.phoneNumber"
                    class="field-input has-prefix"
                    type="tel"
                    placeholder="+1-555-0199"
                    autocomplete="off"
                    :class="{ error: errors.phoneNumber }"
                  />
                </div>
                <span v-if="errors.phoneNumber" class="field-error">{{ errors.phoneNumber }}</span>
              </div>

              <!-- ─────────────────────────────────────────────────────────
                   SECTION: Security
                   Fields: accessPin
                   API shape: { accessPin: string } — stored hashed (bcrypt) by the API.
                   Send the raw PIN; never store or log the plain value on the client.
              ──────────────────────────────────────────────────────────── -->

              <div class="field-row">
                <div class="field-group">
                  <label class="field-label">ACCESS PIN</label>
                  <div class="input-wrap icon-input">
                    <svg class="input-prefix-icon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
                      <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                    </svg>
                    <input
                      v-model="form.accessPin"
                      class="field-input has-prefix"
                      :type="showPin ? 'text' : 'password'"
                      placeholder="4–6 digit PIN"
                      maxlength="6"
                      inputmode="numeric"
                      autocomplete="new-password"
                      :class="{ error: errors.accessPin }"
                    />
                    <!-- Toggle visibility -->
                    <button type="button" class="pin-toggle" @click="showPin = !showPin" :aria-label="showPin ? 'Hide PIN' : 'Show PIN'">
                      <svg v-if="!showPin" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>
                      </svg>
                      <svg v-else width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/>
                        <line x1="1" y1="1" x2="23" y2="23"/>
                      </svg>
                    </button>
                  </div>
                  <span class="field-hint">Numeric only. Stored securely via bcrypt on the server.</span>
                  <span v-if="errors.accessPin" class="field-error">{{ errors.accessPin }}</span>
                </div>

                <!-- PIN Confirm -->
                <div class="field-group">
                  <label class="field-label">CONFIRM PIN</label>
                  <div class="input-wrap icon-input">
                    <svg class="input-prefix-icon" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/>
                    </svg>
                    <input
                      v-model="form.accessPinConfirm"
                      class="field-input has-prefix"
                      :type="showPin ? 'text' : 'password'"
                      placeholder="Re-enter PIN"
                      maxlength="6"
                      inputmode="numeric"
                      autocomplete="new-password"
                      :class="{ error: errors.accessPinConfirm }"
                    />
                  </div>
                  <span v-if="errors.accessPinConfirm" class="field-error">{{ errors.accessPinConfirm }}</span>
                </div>
              </div>

            </div><!-- /form-body -->

            <div class="modal-footer">
              <button class="btn-cancel" @click="$emit('update:modelValue', false)">CANCEL</button>
              <button class="btn-submit" :disabled="submitting" @click="handleSubmit">
                <svg v-if="!submitting" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                  <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/>
                  <line x1="20" y1="8" x2="20" y2="14"/><line x1="23" y1="11" x2="17" y2="11"/>
                </svg>
                <svg v-else class="spin" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                  <path d="M21 12a9 9 0 1 1-6.22-8.56"/>
                </svg>
                {{ submitting ? 'ADDING…' : 'ADD STAFF' }}
              </button>
            </div>

          </div>
        </Transition>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import type { StaffStatus } from './types';

defineProps<{ modelValue: boolean }>();
const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'staff-added', payload: {
    name: string;
    displayName: string;
    role: number;           // role ID for API: { id, roleName }
    shift: string;
    email: string;
    phoneNumber: string;
    employeeId: string;
    accessPin: string;      // plain PIN — API will hash with bcrypt
    avatar: string;
    status: StaffStatus;
  }): void;
}>();

// ── Static data ──────────────────────────────────────────────────────────────
// TODO: fetch roles from GET /api/roles → map to { id: number, label: string }
// API shape: { id: number, roleName: string }
const roles = [
  { id: 1, label: 'Manager'    },
  { id: 2, label: 'Head Chef'  },
  { id: 3, label: 'Sous Chef'  },
  { id: 4, label: 'Line Cook'  },
  { id: 5, label: 'Prep Cook'  },
  { id: 6, label: 'Server'     },
  { id: 7, label: 'Bartender'  },
  { id: 8, label: 'Host'       },
];

const shifts = [
  { label: 'Morning',   display: 'Morning   (06:00 – 14:00)' },
  { label: 'Afternoon', display: 'Afternoon (10:00 – 18:00)' },
  { label: 'Evening',   display: 'Evening   (14:00 – 22:00)' },
  { label: 'Night',     display: 'Night     (22:00 – 06:00)' },
];

// API shape: currentStatus is UPPER_SNAKE_CASE; mapped to StaffStatus (lowercase-kebab) here
const statuses: { value: StaffStatus; label: string }[] = [
  { value: 'active',   label: 'Active'   },
  { value: 'on-break', label: 'On Break' },
  { value: 'off-duty', label: 'Off Duty' },
];

// ── State ────────────────────────────────────────────────────────────────────
const previewUrl = ref('');
const submitting = ref(false);
const showPin    = ref(false);

const form = reactive({
  name:             '',
  displayName:      '',    // API: displayName
  role:             0,     // API: role.id (number)
  shift:            '',
  email:            '',    // API: emailAddress
  phoneNumber:      '',    // API: phoneNumber
  employeeId:       '',    // API: employeeId — auto-assigned if blank
  accessPin:        '',    // API: accessPin (plain; server bcrypts it)
  accessPinConfirm: '',    // client-only confirmation field; NOT sent to API
  status:           'off-duty' as StaffStatus,  // API: currentStatus
});

const errors = reactive({
  name:             '',
  displayName:      '',
  role:             '',
  shift:            '',
  email:            '',
  phoneNumber:      '',
  employeeId:       '',
  accessPin:        '',
  accessPinConfirm: '',
});

// Auto-fill displayName from fullName (e.g. "Marcus Chen" → "Marcus C.")
watch(() => form.name, (val) => {
  if (form.displayName) return; // don't overwrite if user has typed
  const parts = val.trim().split(' ');
  if (parts.length >= 2) {
    form.displayName = `${parts[0]} ${parts[parts.length - 1][0]}.`;
  }
});

function onFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = (ev) => { previewUrl.value = ev.target?.result as string; };
  reader.readAsDataURL(file);
}

function validate(): boolean {
  errors.name             = form.name.trim()         ? '' : 'Full name is required.';
  errors.displayName      = form.displayName.trim()  ? '' : 'Display name is required.';
  errors.role             = form.role                ? '' : 'Please select a role.';
  errors.shift            = form.shift               ? '' : 'Please select a shift.';
  errors.email            = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email) ? '' : 'Enter a valid email.';
  errors.phoneNumber      = form.phoneNumber.trim()  ? '' : 'Phone number is required.';
  errors.employeeId       = ''; // optional — API auto-assigns if blank
  errors.accessPin        = /^\d{4,6}$/.test(form.accessPin) ? '' : 'PIN must be 4–6 digits.';
  errors.accessPinConfirm = form.accessPin === form.accessPinConfirm ? '' : 'PINs do not match.';

  return !Object.values(errors).some(Boolean);
}

function resetForm() {
  Object.assign(form, {
    name: '', displayName: '', role: 0, shift: '', email: '',
    phoneNumber: '', employeeId: '', accessPin: '', accessPinConfirm: '',
    status: 'off-duty',
  });
  previewUrl.value = '';
  showPin.value    = false;
}

async function handleSubmit() {
  if (!validate()) return;
  submitting.value = true;


  await new Promise(r => setTimeout(r, 700)); // simulated network delay

  emit('staff-added', {
    name:        form.name,
    displayName: form.displayName,
    role:        form.role,
    shift:       form.shift,
    email:       form.email,
    phoneNumber: form.phoneNumber,
    employeeId:  form.employeeId,
    accessPin:   form.accessPin,   // NOTE: in production, never log/store this client-side
    avatar:      previewUrl.value,
    status:      form.status,
  });

  resetForm();
  submitting.value = false;
  emit('update:modelValue', false);
}
</script>

<style scoped>
.modal-backdrop {
  position: fixed; inset: 0; z-index: 9999;
  background: rgba(5, 10, 22, 0.78);
  backdrop-filter: blur(6px);
  display: flex; align-items: center; justify-content: center;
  padding: 20px;
}
.modal-card {
  width: 100%; max-width: 520px;
  max-height: 92vh; overflow-y: auto;
  background: #111827;
  border: 1px solid rgba(255,255,255,0.07);
  border-radius: 18px;
  box-shadow: 0 32px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(37,99,235,0.12) inset;
  font-family: 'Plus Jakarta Sans', sans-serif;
}
.modal-header {
  display: flex; align-items: flex-start;
  justify-content: space-between; padding: 28px 28px 0;
  position: sticky; top: 0; background: #111827; z-index: 1;
  border-bottom: 1px solid rgba(255,255,255,0.05);
  padding-bottom: 20px;
}
.modal-title    { font-size: 20px; font-weight: 700; color: #f1f5f9; margin: 0 0 4px; letter-spacing: -0.3px; }
.modal-subtitle { font-size: 13px; color: #475569; margin: 0; }
.modal-close {
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 8px; color: #94a3b8; cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  width: 34px; height: 34px; flex-shrink: 0;
  transition: background 0.15s, color 0.15s; margin-top: 2px;
}
.modal-close:hover { background: rgba(255,255,255,0.1); color: #f1f5f9; }

.avatar-row { display: flex; align-items: center; gap: 18px; padding: 22px 28px 0; }
.avatar-upload {
  width: 72px; height: 72px; min-width: 72px;
  border-radius: 12px; background: #1e293b;
  border: 1.5px dashed rgba(255,255,255,0.12);
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  cursor: pointer; gap: 4px;
  transition: border-color 0.15s, background 0.15s;
  background-size: cover; background-position: center;
}
.avatar-upload:hover       { border-color: #2563eb; background: #1a2540; }
.avatar-upload.has-preview { border-style: solid; border-color: #2563eb; }
.upload-icon  { color: #475569; }
.upload-label { font-size: 9px; font-weight: 700; color: #475569; letter-spacing: 1px; }
.avatar-meta-title { font-size: 11px; font-weight: 700; color: #64748b; letter-spacing: 1px; margin: 0 0 5px; }
.avatar-meta-hint  { font-size: 12px; color: #475569; margin: 0; line-height: 1.5; }

.form-body { display: flex; flex-direction: column; gap: 18px; padding: 22px 28px 0; }
.field-row { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
.field-group { display: flex; flex-direction: column; gap: 6px; }
.field-group.full { grid-column: 1 / -1; }
.field-label { font-size: 11px; font-weight: 700; color: #64748b; letter-spacing: 1px; }
.field-hint  { font-size: 11.5px; color: #334155; margin-top: -2px; }
.input-wrap  { position: relative; }

.field-input {
  width: 100%; background: #1e293b;
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 10px; color: #f1f5f9;
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-size: 14px; padding: 11px 14px;
  box-sizing: border-box; outline: none;
  transition: border-color 0.15s, box-shadow 0.15s;
}
.field-input::placeholder { color: #475569; }
.field-input:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37,99,235,0.18); }
.field-input.error { border-color: #ef4444; }

.field-select { -webkit-appearance: none; appearance: none; padding-right: 36px; cursor: pointer; }
.field-select option { background: #1e293b; }
.select-chevron {
  position: absolute; right: 12px; top: 50%;
  transform: translateY(-50%); color: #475569; pointer-events: none;
}

/* ── Status radio pills ─────────────────────────────── */
.status-options { display: flex; gap: 10px; flex-wrap: wrap; }
.status-option {
  display: inline-flex; align-items: center; gap: 7px;
  padding: 8px 14px; border-radius: 8px;
  border: 1px solid #1e2d45; background: #1a2540;
  font-size: 12px; font-weight: 700; letter-spacing: 0.4px;
  cursor: pointer; transition: all 0.15s;
  color: #64748b; user-select: none;
}
.status-option:hover { border-color: #2d3f5e; color: #94a3b8; }
.status-option.selected.active   { border-color: #166534; background: #052e16; color: #4ade80; }
.status-option.selected.on-break { border-color: #92400e; background: #1c1506; color: #fbbf24; }
.status-option.selected.off-duty { border-color: #ff0000; background: #1e293b; color: #94a3b8; }

.status-dot-sm { width: 7px; height: 7px; border-radius: 50%; flex-shrink: 0; }
.status-dot-sm.active   { background: #4ade80; box-shadow: 0 0 5px #4ade80aa; }
.status-dot-sm.on-break { background: #fbbf24; }
.status-dot-sm.off-duty { background: #ff2a00; }

/* ── Icon prefix inputs ─────────────────────────────── */
.icon-input .input-prefix-icon {
  position: absolute; left: 13px; top: 50%;
  transform: translateY(-50%); color: #475569;
}
.icon-input .has-prefix { padding-left: 36px; }

/* ── PIN toggle button ──────────────────────────────── */
.pin-toggle {
  position: absolute; right: 12px; top: 50%;
  transform: translateY(-50%);
  background: none; border: none; padding: 0;
  color: #475569; cursor: pointer; display: flex;
  transition: color 0.15s;
}
.pin-toggle:hover { color: #94a3b8; }
/* shift right edge of PIN input to avoid overlap with toggle */
.icon-input input.has-prefix { padding-right: 36px; }

.field-error { font-size: 11.5px; color: #f87171; margin-top: -2px; }

.modal-footer {
  display: flex; align-items: center;
  justify-content: flex-end; gap: 12px;
  padding: 24px 28px 28px;
  position: sticky; bottom: 0; background: #111827;
  border-top: 1px solid rgba(255,255,255,0.05);
  margin-top: 22px;
}
.btn-cancel {
  background: transparent; border: none; color: #64748b;
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-size: 13px; font-weight: 700; letter-spacing: 0.5px;
  cursor: pointer; padding: 11px 18px; border-radius: 10px;
  transition: color 0.15s, background 0.15s;
}
.btn-cancel:hover { background: rgba(255,255,255,0.05); color: #94a3b8; }
.btn-submit {
  display: flex; align-items: center; gap: 8px;
  background: #2563eb; color: #fff;
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-size: 13px; font-weight: 700; letter-spacing: 0.5px;
  padding: 11px 22px; border-radius: 10px; border: none;
  cursor: pointer; transition: background 0.15s, opacity 0.15s;
}
.btn-submit:hover:not(:disabled) { background: #1d4ed8; }
.btn-submit:disabled { opacity: 0.6; cursor: not-allowed; }
.spin { animation: spin 0.8s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }

.modal-fade-enter-active, .modal-fade-leave-active { transition: opacity 0.22s ease; }
.modal-fade-enter-from,   .modal-fade-leave-to     { opacity: 0; }
.modal-slide-enter-active { transition: opacity 0.22s ease, transform 0.22s cubic-bezier(0.34,1.56,0.64,1); }
.modal-slide-leave-active { transition: opacity 0.18s ease, transform 0.18s ease; }
.modal-slide-enter-from   { opacity: 0; transform: scale(0.94) translateY(10px); }
.modal-slide-leave-to     { opacity: 0; transform: scale(0.97) translateY(6px); }
</style>