name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies and build test
        run: |
          npm install
          npm run build
          
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 13.229.77.211
          username: ubuntu
          key: ${{ secrets.UI_EC2_SSH_KEY }}
          source: "."
          target: "~/deploy-ui"
          
      - name: Build and Run with Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.229.77.211
          username: ubuntu
          key: ${{ secrets.UI_EC2_SSH_KEY }}
          script: |
            cd ~/deploy-ui
            docker rm -f ui-rest || true
            docker compose down --remove-orphans || true
            docker compose up -d --build
            docker image prune -f

      - name: Send Telegram Notification (Success)
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ DEPLOYMENT SUCCESS ✅
            ------------------------------------
            🚀 Application: ui-rest
            🔗 Live URL: https://ui.learner-teach.online
            👤 Author: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}
            ------------------------------------
            Awesome job, ${{ github.actor }}! The frontend deployment is fully live! 🎉
          document: "https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif"

      - name: Send Telegram Notification (Failure)
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ DEPLOYMENT FAILED ❌
            ------------------------------------
            🚀 Application: ui-rest
            👤 Author: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}
            ------------------------------------
            Hey ${{ github.actor }}, the deployment pipeline failed.
            🔍 Review the logs here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          document: "https://media.giphy.com/media/T1WqKkLYCbC12/giphy.gif"
